const ApiRoutes = {
    LOGIN:{
        path:'/users/login',
        authenticate:false
    },
    SIGNUP:{
        path:'/users/createUser',
        authenticate:false
    },
    GET_ALL_USERS:{
        path:'/users/getallusers',
        authenticate:true
    },
    GET_USER_BY_ID:{
        path:'/users/getuserbyid',
        authenticate:true
    },
    EDIT_USER_BY_ID:{
        path:'/users/edituserbyid',
        authenticate:true
    },
    UPDATE_STATUS:{
        path:'/vehicles/updatestatus',
        authenticate:true
    },
    USERS_UPDATE_STATUS:{
        path:'/users/updatestatus',
        authenticate:true
    },
    GET_ALL_VEHICLES:{
        path:'/vehicles/getallvehicles',
        authenticate:true
    },
    GET_ALL_APPROVED_VEHICLES:{
        path:'/vehicles/getallapprovedvehicles',
        authenticate:true
    },
    GET_VEHICLE_BY_USERID:{
        path:'/vehicles/getvehiclesbyuserid',
        authenticate:true
    },
    ADD_VEHICLE:{
        path:'/vehicles/addvehicle',
        authenticate:true
    },
    GET_VEHICLE_BY_LOCATION:{
        path:'/vehicles/getvehiclesbylocation',
        authenticate:true
    },
    BOOK_CAR:
    {
        path:'/booking/bookcar',
        authenticate:true
    },
    GET_VEHICLE_BY_ID:
    {
        path:'/vehicles/getvehiclebyid',
        authenticate:true
    },
    GET_BOOKING_BY_USERID:
    {
        path:'/booking/getbookingbyuserid',
        authenticate:true
    },
    GET_ALL_BOOKINGS:
    {
        path:'/booking/getallbookings',
        authenticate:true
    },
    ADD_CONTACT:
    {
        path:'/contact/addcontact',
        authenticate:true
    }
}


export default ApiRoutes